### ISSUE TITLE
ollama support?

### ISSUE THREAD

**Issue by BarfingLemurs** [bevren/simple-chat-pdf#1]
Cool pdf explorer! Was ollama supported in the code? I was hoping to use it since I don't have an openai key for the embeddings.

**Comment by bevren** [comment]
thanks. i am working on ollama right now, i will release it soon.

**Comment by bevren** [comment]
it seems to be working. i have a very old laptop so it takes a long time to create embeddings using ollama. can you please try it?

**Comment by BarfingLemurs** [comment]
I set the embeddings to ollama, model as nomic-embed-text, it couldnt find any rag input after loading the pdf. I'm using it with groq as the provider.

**Comment by bevren** [comment]
probably state of the application cached in localStorage. open developer tools > application > storage and delete the "app" key then refresh the page. i have tried with groq and it works fine.

**Comment by BarfingLemurs** [comment]
Then it's probably something on my end, what is the URL and model name I should add? Mine: http://localhost:11434 , nomic-embed-text:latest

I checked if ollama communicates correctly with the page assist browser extension. I'm using ubuntu Linux running chrome. I went through f12 > application > local storage > delete app

**Comment by bevren** [comment]
sorry i pushed the wrong version. now it should work. if still not working it can be CORS issue. 

https://medium.com/dcoderai/how-to-handle-cors-settings-in-ollama-a-comprehensive-guide-ee2a5a1beef0

follow this link to set environment variables.

**Comment by BarfingLemurs** [comment]
Thanks, I still couldn't figure ollama out for this on the latest, if you confirmed it already works, that's good enough for me.
